### ISSUE TITLE
Verwaister Link

### ISSUE THREAD

**Issue by bruno-thurnherr** [nds-swe/swdt#34]
Hallo Dominik

Unter der URL https://nds-swe.github.io/swdt/docs/tasks/client-server/   funktioniert der Absprung unter dem Wort DevOps nciht.

Head over to our **DevOps** section and follow the Atlassian resource. Read the complete overview.### 

Hinterlegter Link:     https://nds-swe.github.io/swdt/docs/tasks/client-server/docs/theory/devops

Fehlermeldung:
![image](https://user-images.githubusercontent.com/82406567/115015337-c6687080-9eb3-11eb-880d-b3bab5278297.png)

Liebe Grüsse
Bruno

**Comment by mambax** [comment]
@bruno-thurnherr Thank you for the report. I added a fix and added you as reviewer, have a look 🤝 
I will wait some days for your approval and then I will merge 😉
